<?php

$viewModel = $block->getViewModel();
?>
<?= $block->escapeUrl($block->getFormAction()) ?>
<h2>From Custom Form</h2>
<form class="form contact"
    action="<?= $block->escapeUrl($block->getFormAction()) ?>"
    id="contact-form"
    method="post"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation":{}}'>

    <div class="container campweb-contact-us">
        <div class="row ">
            <div class="col-md-6 contact-us-content">
                <fieldset class="fieldset">
                    <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
                    <div class="field note no-label">
                        <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
                    </div>
                    <div class="field name required">
                        <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                        <div class="control">
                            <input name="name"
                                id="name"
                                title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                                class="input-text"
                                type="text"
                                data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input name="email"
                                id="email"
                                title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                                class="input-text"
                                type="email"
                                data-validate="{required:true, 'validate-email':true}"
                                data-mage-init='{"mage/trim-input":{}}'
                            />
                        </div>
                    </div>
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div class="control">
                            <input name="telephone"
                                id="telephone"
                                title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                                class="input-text"
                                type="tel" />
                        </div>
                    </div>
                    <div class="field comment required">
                        <label class="label" for="comment">
                            <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
                        </label>
                        <div class="control">
                            <textarea name="comment"
                                    id="comment"
                                    title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                                    class="input-text"
                                    cols="5"
                                    rows="3"
                                    data-validate="{required:true}"
                            ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
                        </div>
                    </div>
                    <?= $block->getChildHtml('form.additional.info') ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value="" />
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-6 contact-us-image">
                <img src="https://statusneo.com/wp-content/uploads/2023/02/MicrosoftTeams-image551ad57e01403f080a9df51975ac40b6efba82553c323a742b42b1c71c1e45f1.jpg" width="200px" height="200px"/>
            </div>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
