<?php
    use Magento\Bundle\ViewModel\ValidateQuantity;
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php
    $_option = $block->getOption();
    $customBlock = $this->getLayout()->createBlock(\Logicrays\IncreaseQty\Block\GeneralData::class);
    $isStockManage = $customBlock->isStockManage();
?>

<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php
/** @var ValidateQuantity $viewModel */
$viewModel = $block->getData('validateQuantityViewModel');
?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                <input type="hidden"
                    class="bundle-option-<?= (int)$_option->getId() ?>  product bundle option"
                    name="bundle_option[<?= (int)$_option->getId() ?>]"
                    value="<?= (int)$_selections[0]->getSelectionId() ?>"
                    id="bundle-option-<?= (int)$_option->getId() ?>-<?= (int)$_selections[0]->getSelectionId() ?>"
                    checked="checked"
                />
                <?php
                $adminQty = $customBlock->getStockItem($_selections[0]->getProductId());
                if ($adminQty['use_config_manage_stock']) {
                    if ($isStockManage) {
                        $adminStockManageQty = $adminQty['qty'];
                    } else {
                        $adminStockManageQty = $adminQty['qty'].'_0';
                    }
                } elseif ($adminQty['manage_stock']) {
                    $adminStockManageQty = $adminQty['qty'];
                } else {
                    $adminStockManageQty = $adminQty['qty'].'_0';
                }
                ?>
                <input type="text" id="bundle-option-qty-input<?= /** */ $_option->getId() ?>"
                value="<?= /* @noEscape */ $adminStockManageQty?>" hidden/>
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <div class="field choice">
                        <input type="radio"
                               class="radio product bundle option"
                               id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                               name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                               data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                               <?= ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                               value=""/>
                        <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
                            <span><?= $block->escapeHtml(__('None')) ?></span>
                        </label>
                    </div>
                <?php endif; ?>
                <?php $i=0?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php
                    $adminQty = $customBlock->getStockItem($_selection->getProductId());
                    // echo 'adminQty '.$adminQty['qty'];
                    if ($adminQty['use_config_manage_stock']) {
                        if ($isStockManage) {
                            $adminStockManageQty = $adminQty['qty'];
                        } else {
                            $adminStockManageQty = $adminQty['qty'].'_0';
                        }
                    } elseif ($adminQty['manage_stock']) {
                        $adminStockManageQty = $adminQty['qty'];
                    } else {
                        $adminStockManageQty = $adminQty['qty'].'_0';
                    }
                    ?>
                    <div class="field choice">
                        <input type="radio"
                            class="radio product bundle option change-container-classname bundle-option-radio-change"
                            data-text="<?= /** noEscap */ $adminStockManageQty?>"
                            id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            <?php if ($_option->getRequired()) { echo 'data-validate="{\'validate-one-required-by-name\':true}"'; }?>
                            name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                            <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>
                            value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"/>
                        <label class="label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionTitlePrice($_selection) ?></span>
                            <br/>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                        </label>
                    </div>
                    <?php $i++?>
                <?php endforeach; ?>
                <input type="text" class="bundle-option-qty-input-values"
                    id="bundle-option-qty-input<?= /** */ $_option->getId()?>"
                    value="" hidden/>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
            <?php endif; ?>
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Quantity')) ?></span>
                </label>
                <div class="control">
                    <button <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                        onclick="decreaseQty(<?= /** noEscap */ $_option->getId() ?>); return false;"
                        class="decreaseQty decrease-btn-action_<?= /** noEscap */ $_option->getId() ?>"
                        title="Decrease Qty" data-target="bundle-option-<?= $_option->getId()?>-qty-input">-</button>

                    <input <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                        id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                        class="bundleqty input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>"
                        type="number"
                        min="0"
                        data-validate="<?= $block->escapeHtmlAttr($viewModel->getQuantityValidators()) ?>"
                        name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                        data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                        value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"/>

                    <button <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                        onclick="increaseQty(<?= /** noEscap */ $_option->getId() ?>); return false;"
                        class="increaseQty increaseQty-radio-select increase-btn-action_<?= /** noEscap */ $_option->getId() ?>"
                        title="Increase Qty" data-target="bundle-option-<?= /** noEscap */ $_option->getId()?>-qty-input">+</button>
                </div>
            </div>
        </div>
    </div>
</div>
